### ISSUE TITLE
AnyVideo downloads wrong file extension

### ISSUE THREAD

**Issue by CUR5EDFLVME** [z1nc0r3/AnyVideo-Downloader-Flow-Plugin#10]
![image](https://github.com/user-attachments/assets/36b74862-24c7-4e45-8b0c-f7e0e4d9de0a)

Flow launcher windows says that I pick an mp4 file, but it downloads it in mkv, which can't natively be displayed by discord. I can ofc manually change .mkv to .mp4, but it's not as convenient as it could be.

Also, idk where can I write my suggestions, so I'll write it here:
- It would be great to see the file size of the thing i try to download, because I usually send memes to my homies on discord, but I don't have any nitro premium subscriptions, so I need to be sure that files I try save to send aren't bigger than 10Mb. (important thing)
- It would be a bit better imo, if you could set preferences in settings for preferred file formats, something like include only audio/only video items on the list and things like that. Because the list sometimes is so big and it becomes a bit hard to pick the right one. Maybe you could show some preferred items and then give "show more" option which would show all the items. Here's a screenshot how a different plugin shows download options, it's very simple, a bit extremely too simple, but it's easier to make a choice of 2 options, instead of 20-30 different ones(It's not a very important thing, but yeah, it would be good as an option)
![image](https://github.com/user-attachments/assets/678f72f9-413e-42ef-84af-d7531f479ade)

But still, thank you for your work on this plugin.

**Comment by z1nc0r3** [comment]
Hi @CUR5EDFLVME, a new version has been released with a few enhancements. Users now can set preferred video/audio formats, so the files will be downloaded in that format. So I hope this release will partially fix this issue.

Regarding the suggestion, I plan to introduce a `simple mode` that will allow users to quickly download the highest quality video and audio files without having to navigate through the entire list. I'm not sure when this feature will be available, though. So I'll keep this issue open for now.

Please check out the new release, and feel free to report any issues or suggestions. Thank you!

**Comment by CUR5EDFLVME** [comment]
Yo, I checked the new version 2.0.0, and I like all these new settings options and file size information. Very good update, my issue is mostly resolved and all these new features are great. It could be a bit improved still by making the program somehow automatically check what's the default folder for downloads set by user in windows settings, but it's not necessary, because you you can see now where the file would be saved and can change the folder in settings by your own.
![image](https://github.com/user-attachments/assets/e52a4be3-e970-4b6c-8556-14ffdfc0e17f)

Everything looks very cool, except I stumbled upon one other issue(I'll open a new issue ticket for that).
