### ISSUE TITLE
Video name

### ISSUE THREAD

**Issue by Rockyest** [z1nc0r3/AnyVideo-Downloader-Flow-Plugin#20]
Can you think about supporting Unicode characters for names? It appears as a _

**Comment by z1nc0r3** [comment]
In the download command, I've used some flags like
- `--windows-filenames`
- `--restrict-filenames`
- `--trim-filenames 50`

which controls the way that the files are saved. The reason I added those flags is I found some cases in which the video contained some characters not supported by Windows OS and so it fails to create or delete the files.

I have an idea to add settings for the above flags, so users can decide whether to use them or not.

But for now, If possible please comment the video URL you're trying to download, or else you can try removing the `--windows-filenames` and `--restrict-filenames` flags from the [code](https://github.com/z1nc0r3/AnyVideo-Downloader-Flow-Plugin/blob/6b47cda8c016e9966db777b51b0b07cd3e8fa1e7/plugin/main.py#L179-L197) to check it works correctly.

**Comment by Rockyest** [comment]
Thanks so much!

**Comment by Rockyest** [comment]
Thanks so much!

**Comment by Rockyest** [comment]
Does --trim-filenames 50 restrict the names? And can I change the 50 or delete the line?

**Comment by z1nc0r3** [comment]
You can check the parameter details [here](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#filesystem-options)
