### ISSUE TITLE
mp3?

### ISSUE THREAD

**Issue by EsdrubalMagano** [z1nc0r3/AnyVideo-Downloader-Flow-Plugin#5]
Hey,

Love the plugin, nice work!

I wonder if you could specify the audio format of "audio-only." I need mp3 for my workflow, and converting from m4a to mp3 is not ideal. I don't know if the youtube-dl allows that. Hopefully, it does.

Anyway, keep up the excellent work!

**Comment by z1nc0r3** [comment]
Hi, Thanks for using this plugin and for the suggestion 🚀

I thought it depended on the video provider currently. I'll try adding the format for the result's subtitle so we can see the file format. And I'll go through the docs later to see what we can do.

**Comment by z1nc0r3** [comment]
Hi @EsdrubalMagano, a new version has been released (v2.0.0) with the support of `preferred video/audio format` which can be set from the plugin's settings page. All the files will be downloaded as the preferred file format.

Check out the new version and report any issues or suggestions. Thank you!
