### ISSUE TITLE
What format am I downloading this file in?

### ISSUE THREAD

**Issue by Woysful** [z1nc0r3/AnyVideo-Downloader-Flow-Plugin#6]
I really like this addon, in theory it could speed up my work a lot. But every time I download a video file, I don't know its format. It is often .webm, which is unacceptable for me, because my work environment can not work with this video format. Because of this I have to download each new video from the list until I get to a format I can accept. This causes a lot of frustration and wastes a lot of time.

It would be very useful to know before downloading in what format the proposed video file, or to be able to disable the output to the list of formats not used by the user.

I hope this feedback will help to improve the addon. Thanks for your work!

**Comment by z1nc0r3** [comment]
Thank you for the feedback. I've had this idea for a while but didn't have much time to work on it. A new version will be released soon with this feature so users will be able to see the file format on the subtitle.

Thank you for using this plugin!!!
