### ISSUE TITLE
Plugin saves videos to a bit wrong folder.

### ISSUE THREAD

**Issue by CUR5EDFLVME** [z1nc0r3/AnyVideo-Downloader-Flow-Plugin#9]
![image](https://github.com/user-attachments/assets/1231383f-8aa6-4cbb-835d-1e43503f9a08)

Windows allows users to change the location of system folders like downloads, videos, documents, etc. But for some reason plugin doesn't download items to the actual location. Here you can see that my downloads folder actually locates on the disk F:/, but plugin saved videos to the disk C:/.
I spent a bit too much time trying to figure this out.

**Comment by z1nc0r3** [comment]
Thanks for the issue!
From the `v2.0.0` onwards, users can set custom download locations.
